# Filtrado

En este notebook aprenderás a implementar filtros sobre una imagen.

### Filtrado o convolución de imágenes

Es la operación más importante de visión computacional. Permite encontrar representaciones en diferentes escalas de una imagen. Es el ingrediente principal de la visión computacional moderna (de ahí el nombre de redes neuronales convolucionales). Veamos como se implementa una función de convolución para entender su funcionamiento.

In [1]:
import numpy as np
import cv2
import plotly.express as px

In [2]:
!wget https://ivan-sipiran.com/downloads/Imagenes.zip
!unzip Imagenes.zip

--2025-08-22 18:44:03--  https://ivan-sipiran.com/downloads/Imagenes.zip
Resolving ivan-sipiran.com (ivan-sipiran.com)... 66.96.149.31
Connecting to ivan-sipiran.com (ivan-sipiran.com)|66.96.149.31|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30654084 (29M) [application/zip]
Saving to: ‘Imagenes.zip’

Imagenes.zip        100%[===================>]  29.23M  10.4MB/s    in 2.8s    

2025-08-22 18:44:07 (10.4 MB/s) - ‘Imagenes.zip’ saved [30654084/30654084]

Archive:  Imagenes.zip
   creating: Imagenes/
  inflating: Imagenes/20191123_093200.jpg  
  inflating: Imagenes/Aviones.jpg    
  inflating: Imagenes/bird.png       
  inflating: Imagenes/cameraman.tif  
  inflating: Imagenes/centro1.jpg    
  inflating: Imagenes/centro2.png    
  inflating: Imagenes/claro.png      
  inflating: Imagenes/contrast1.jpg  
  inflating: Imagenes/contrast2.jpeg  
  inflating: Imagenes/contrast3.jpg  
  inflating: Imagenes/diagonalbars.png  
  inflating: Imagenes/digits.png     

In [3]:
""" Funcion que calcula la convolución de una imagen con un filtro (kernel)
Los filtros son siempre de tamaño impar """

def convolucion2D(imagen, filtro):
    # Zero padding

    ## Desplazamientos para aplicar filtros en los bordes la imagen
    shift_row = filtro.shape[0]//2
    shift_col = filtro.shape[1]//2

    ## Se crea una nueva imagen con ceros
    new_image = np.zeros((imagen.shape[0] + 2*shift_row, imagen.shape[1] + 2*shift_col), np.float32)

    ## Se coloca la imagen original en el centro de la nueva
    new_image[shift_row : imagen.shape[0]+shift_row,shift_col : imagen.shape[1]+shift_col] = imagen

    ## Obtenemos el tamaño de la imagen resultante
    new_image2 = np.zeros((new_image.shape[0], new_image.shape[1]), np.float32)

    # Aplicar filtrado

    ## Recorremos sobre cada pixel de la imagen original
    for i in range(shift_row, imagen.shape[0]+shift_row):
        for j in range(shift_col, imagen.shape[1]+shift_col):

          ## Para cada pixel se extrae un sub-bloque con dimensiones igual al filtro
          aux = new_image[i-shift_row : i+shift_row+1, j-shift_col : j+shift_col+1]

          ## Aquí ocurre la convolución: Se multiplica el sub-bloque por el filtro y se suma
          new_image2[i,j] = np.sum(aux*filtro)

    ## Devuelve una imagen con las mismas dimensiones que la original, sin el padding que agregamos antes
    return new_image2[shift_row:imagen.shape[0]+shift_row,shift_col:imagen.shape[1]+shift_col]

### Filtro Promedio 1

In [15]:
# Aplicamos la convolucion con un filtro en donde todos los pesos son iguales
im = cv2.imread('Imagenes/lorito.jpg',0)
tamFiltro = 11

print(1/(tamFiltro**2))
print(np.ones((tamFiltro,tamFiltro)))

filtro = (1/(tamFiltro**2)) * np.ones((tamFiltro,tamFiltro))

print(filtro)

im2 = convolucion2D(im, filtro)

salida = np.concatenate((im, im2), axis=1)
px.imshow(salida, binary_string=True).show()

0.008264462809917356
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.00826446 0.00826446 0.00826446 0.00826446 0.00826446]
 [0.00826446 0.00826446 0.00826446 0.00826446 0.00826446 0.00826446
  0.008264

In [5]:
tams = [5,7,9,11,15,17]
imgs = []

for i, tam in enumerate(tams):
  filter = (1/(tam**2))*np.ones((tam,tam))
  img = convolucion2D(im, filter)
  imgs.append(img)

px.imshow(np.concatenate(tuple(imgs), axis=1), binary_string=True).show()

El filtro visto arriba es un filtro de promedio. Lo que hace es promediar los valores de color en una vecindad, por eso crea un efecto de blur.
Pero la convolución también puede servir para realzar los detalles de una imagen.
Mientras más grande el tamaño del filtro se pierde el detalle de los bordes. El promedio incluye muchas más área.

### Filtro Promedio 2

In [16]:
# Aplicamos la convolucion con un filtro en donde todos los pesos son iguales
im = cv2.imread('Imagenes/lorito.jpg',0)
tamFiltro = 5
filtro = (1/(tamFiltro**2)) * np.ones((tamFiltro,tamFiltro))

## ddepth se utiliza para indicar la profundidad de la imagen, en este caso,
## la misma de la imagen de entrada
im2 = cv2.filter2D(im, ddepth=-1, kernel=filtro)

salida = np.concatenate((im, im2), axis=1)
px.imshow(salida, binary_string=True).show()

In [17]:
tams = [5,7,9,11,15,17]
imgs = []

for i, tam in enumerate(tams):
  filter = (1/(tam**2))*np.ones((tam,tam))
  img = cv2.filter2D(im, ddepth=-1, kernel=filter)
  imgs.append(img)

px.imshow(np.concatenate(tuple(imgs), axis=1), binary_string=True).show()

### Filtro Laplaciano

Agrega detalle a la imagen.

Particulamente, detecta cambios bruscos en las intensidad: bordes, lineas, detalles finos.

In [19]:
# Filtro Laplaciano
im = cv2.imread('Imagenes/moon.jpg', 0)

# Aproximación discreta del operador Laplaciano.
# Calcula la segunda derivada de una imagen.
filtro = np.array([[0, 1,0],
                   [1,-4,1],
                   [0, 1,0]])

laplacian = convolucion2D(im, filtro)

# Se resta la imagen de bordes y la imagen original
# Se resta porque la convolución devuelve valores negativos
out = im - laplacian

# Normalizamos en un rango de 0 a 255
np.clip(laplacian, 0, 255, out = laplacian)
laplacian = laplacian.astype('uint8')

np.clip(out, 0, 255, out = out)
out = out.astype('uint8')

px.imshow(np.concatenate((im,laplacian,out),axis=1),binary_string=True).show()

### Filtro Sobel

A diferencia del filtro Laplacian, el filtro Sobel calcula la primera derivada (gradiente) de la imagen en dos direcciones:


*   Borde vertical: Derivada en X
*   Borde horizontal: Derivada en y

El Laplaciano calcula la segunda derivada de la imagen (suma las derivadas en X y en Y.

En sintesis:


*   Sobel: Detecta los bordes con dirección.
*   Laplacian: Detecta bordes generales mediante cambios en la intensidad.



In [21]:
im = cv2.imread('Imagenes/moon.jpg', 0)

# Filtro Sobel
filtro_x = np.array([[-1,0,1],
                    [-2,0,2],
                    [-1,0,1]])

sobel_x = cv2.filter2D(im, ddepth=-1, kernel=filtro_x)

out_x = np.clip(sobel_x, 0, 255)
out_x = out_x.astype('uint8')

px.imshow(out_x, binary_string=True).show()

### Ejercicio 1

* Aplicar el filtrado Sobel en el eje "*y*" para obtener los bordes horizontales.

In [22]:
filtro_y = np.array([[-1,-2,-1]
                   ,[0,0,0]
                   ,[1,2,1]])

sobel_y = cv2.filter2D(im, ddepth=-1, kernel=filtro_y)

out_y = np.clip(sobel_y, 0, 255)
out_y = out_y.astype('uint8')

px.imshow(out_y, binary_string=True).show()

### Ejercicio 2

* ¿Cómo obtener una sola imágen con los bordes detectados en ambas direcciones?.

In [23]:
sobel_xy = np.sqrt(sobel_x**2 + sobel_y**2)

out_xy = np.clip(sobel_xy, 0, 255)
out_xy = out_xy.astype('uint8')

px.imshow(out_xy, binary_string=True).show()

### Detector de borde Canny

Nota:


*   Sigma pequeño → bordes finos y detallados, pero más ruido.
*   Sigma grande → bordes más limpios y gruesos, pero se pierden detalles.

In [24]:
# --- Canny con umbrales automáticos vía mediana ---
def auto_canny(gray, sigma=0.33):

    ## Calcula la mediana de intensidades de la imagen
    v = np.median(gray)

    ## Umbral inferior
    lower = int(max(0, (1.0 - sigma) * v))

    ## Umbral superior
    upper = int(min(255, (1.0 + sigma) * v))

    edges = cv2.Canny(gray, lower, upper, L2gradient=True)
    return edges, (lower, upper)

im = cv2.imread('Imagenes/lorito.jpg', 0)
edges_list = []
params = []

for s in [0.5, 1.0, 1.5, 2.0]: # 1.2

    ## Suaviza con gaussiano de sigma=s
    blur = cv2.GaussianBlur(im, (0,0), s)

    ## Sigma controla que tan amplios van a ser los umbrales alrededor de la mediana
    ed, (lo, hi) = auto_canny(blur, sigma=0.33)
    edges_list.append(ed) # Bordes detectados
    params.append((lo, hi, s)) # Parametros

px.imshow(np.concatenate(tuple(edges_list), axis=1), binary_string=True,
          title=f"Canny con suavizado previo sigmas={[p[2] for p in params]}").show()
